### PR TITLE
New option 'forceChangeEvent'

### PR DESCRIPTION
**Pull request by Draeli**
New option 'forceChangeEvent' to force fire event change even when color is the same.
To 'resolve' #326

### CODE REVIEW

**Comment by avoliva** [comment]
I'm curious, is there a reason to have the `hasChanged` boolean in the first place? Couldn't it just fire it all the time without this extra flag?

**Comment by Draeli** [comment]
Fire all time can result in recursive loop in few case, by the way, the best is to stop if color no change and to have a flag for special case (in my case I need to implement double palette and bypass a part of color picker). I change the flag above to optimize calcul and not resolve color equality if flag is "true".

**Comment by bgrins** [comment]
I don't understand why change should fire when nothing changed.  Is this to work around the bug in which the change event fires when a palette item is clicked?  Because we should fix that issue as outlined in https://github.com/bgrins/spectrum/issues/250#issuecomment-66397975, and maybe it would make this option not needed?

**Comment by Draeli** [comment]
For example (and it's only one of mine), I have a double palette (something I do out of the plugin), in first one, I have some colors and in the other, depending on the first, I have others colors, when I click on the second I want to refresh event if color not appear to change to force refresh, the problem actually I the plugin and it's not a good practice, is to stop propagation.
Is never good to decide for other developper what must do, plugin do what is must do but if a developper want to be able to work over the plugin, it must be able to do without problem, which is my problem actually (is spite the code is good, I saw some anti-pattern).

**Comment by bgrins** [comment]
> in first one, I have some colors and in the other, depending on the first, I have others colors, when I click on the second I want to refresh event if color not appear to change to force refresh, the problem actually I the plugin and it's not a good practice, is to stop propagation.

So if I understand correctly, you are wanting an event when any palette element is clicked on for the left one even if it hasn't changed?  I have a work in progress that *might* help with this use case in #405.  Can you pull down this version and listen to the 'move' event instead of 'change': https://raw.githubusercontent.com/bgrins/spectrum/palette-change/spectrum.js.   It should be firing ever time you click on a palette item even if it's unchanged.

**Comment by avoliva** [comment]
What about an `onSubmit` event that fires when the Choose button is clicked. Someone brought this up in #403 too.

**Comment by bgrins** [comment]
@avoliva I think with the changes in #405 (https://raw.githubusercontent.com/bgrins/spectrum/palette-change/spectrum.js) that will make the 'change' event basically like an 'onSubmit' event (with the difference that 'change' will also fire on clickout if clickoutFiresChange is true)

**Comment by Draeli** [comment]
I resolve an issue in case input color is inside label tag, in this case, in spite input was hide, click event on label tag fire color input. Now, event is intercept and picker is fire correctly.

**Comment by bgrins** [comment]
>  I resolve an issue in case input color is inside label tag, in this case, in spite input was hide, click event on label tag fire color input. Now, event is intercept and picker is fire correctly.

Sorry, I'm not following exactly.  Are you saying the version of the spectrum.js I mention in the previous comment (https://github.com/bgrins/spectrum/pull/402#issuecomment-199602963) fixed your issue?

**Comment by Draeli** [comment]
Sorry I push on this branch a lot of things ... I didn't test yet the version you say.

**Comment by bgrins** [comment]
The changes in #405 which are now on master should allow you to listen to a 'move' event for *any* change and a 'change' event for submission.  I believe this covers the behavior in the PR, so going to close it out.  Thanks for the discussion here, it helped come up with what I think is a good set of changes.  Let me know if the latest master still doesn't cover your use case.

**Pull request closed without merging**
