### PR TITLE
added main script for use with browserify

### PR DESCRIPTION
**Pull request by fgandellini**

### CODE REVIEW

**Comment by bgrins** [comment]
Cool, is there anything else we should do in the library / documentation to use this with browserify or does it just work with this `main` field?

**Comment by fgandellini** [comment]
As far as I know, the `main` field is mandatory in order to let browserify to bundle the main file of your module. 

To use spectrum with browserify, you need to require it like this:
```javascript
require('spectrum-colorpicker')(jQuery);
```
because the library exports the factory function, and then you can use it as usual:
```javascript
$('#spectrum-container').spectrum(opts);
```
And it works (you always need to include spectrum css).

In fact, this is not the standard way to use browserify components, usually is useful to export a constructor-like function, this let you to use the component like this:

```javascript
var Spectrum = require('spectrum-colorpicker');
var spectrum = new Spectrum('#spectrum-container', opts); // this is only an example...
```
but in this case, maybe, is not so easy to use spectrum like a jQuery plugin. This changes the way a jQuery user expects to use it...

This is the main cause because I didn't modified the behaviour of the library.

If you need some more info about ComponentJS (a.k.a. browserify compatible) modules, you can look here: 
https://github.com/umdjs/umd
http://addyosmani.com/writing-modular-js/
http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html

**Comment by markgoodyear** [comment]
@fgandellini @bgrins I've just come across this issue with Webpack also. Without the `main` attribute, the module cannot be resolved. Adding it in and it worked perfectly. Would be great to see this merged in.

**Comment by briancappello** [comment]
+1 for webpack. Any chance of getting this merged? Would love to be able to use this library! Thanks @bgrins :+1:

**Comment by bgrins** [comment]
Sorry for dropping the ball here, I merged in the change in #335

**Comment by briancappello** [comment]
@bgrins Awesome thank you!

**Pull request closed without merging**
