### PR TITLE
Input for setting RGB in separate inputs for each color component

### PR DESCRIPTION
**Pull request by KozzyKoder**
I supposed that functionality of editing RGB components in separate control elements of colorpicker  is much more user-friendly.

### CODE REVIEW

**Comment by KozzyKoder** [comment]
Here is an example of new control:
screenshot on 11 24 2015 at 10 18 56 pm

**Comment by Horray** [comment]
Really like that idea!

Were you able to implement that?

**Comment by KozzyKoder** [comment]
This feature already completely implemented, but I have 2 small questions:
1) what behaviour is desired for input validation? Now all out-of-range components input(0-255) is set to nearest bound. For example 555 is set to 255 to fit range of possible values. Any non-digit input cause inputs to become red.
2) one small question about markup: is it desired behaviour that bootstrap adds margin under inputs? I saw styles in project css that sets that margin to 0, but this styles didn't apply because of specifity.

**Comment by Horray** [comment]
Thanks! I didn't get how github works with the updates. But I now got it. I really like the way you did it! 

I tried doing it myself, and was working on it for a couple of day, then stumbled on this. I was almost done, but chose this :)

To answer your questions:

1) The desired behavior would be to not allow any 'illegal' values. If you set the text `input`'s `maxlength` to 3, (which I recommend you update it with `maxlength=3`) and you try to add a fourth char, it won't let you. That's how I want the input validation to be.

2) I don't use bootstrap, so I can't answer that question.

Thanks! All the best!

**Comment by bgrins** [comment]
Thanks for the interest in this feature and putting together the PR (including tests and docs!).  I have a couple of challenges here with accepting this:

* Taking on additional options adds complexity to the frontend and all the different permutations that can happen.  As an example, with these change applied the normal input field is no longer lining up with the initial swatches (they are meant to be on the same line)

screenshot 2015-12-15 10 39 12

* I'm unsure of how this should interact with semi-transparent colors - like, should an 'A' field also show up in that case?
* I could see people also wanting this ability to fit in with whatever their preferred color format is, like if I set the vale to an HSL color then why shouldn't there be discreet fields for each of those?

I'm afraid that taking this on will add a fair amount of extra maintenance, and it's already a challenge for me to support the existing API.

**Comment by KozzyKoder** [comment]
Thank you for your response! In my opinion, your argument regarding to maintenance complexity is wise(it is already really wide range of options in your project). Actually, I implemented this feature because I really need it in my current project and decided to share this one with community. It was not hard enough, because of quite good architecture, so anybody who want such feature can easily implement it by themselves or use my fork as an example.

**Comment by bgrins** [comment]
Thanks for understanding, and if I see requests for this I will point people to your patch

**Pull request closed without merging**
